version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vedic
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
