[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[context.production.environment]
  # Set the backend API URL in Netlify settings or override here
  NEXT_PUBLIC_API_BASE_URL = ""
