"""
Vedic Astrology Interpretations Database.
Contains classical interpretations for Planets in Signs and Houses.
"""

PLANETS_IN_SIGNS = {
    "Sun": {
        "Aries": "Sun in Aries is exalted. You are a born leader, energetic, ambitious, and confident. You may be impatient but possess great vitality.",
        "Taurus": "Sun in Taurus gives a stable, practical nature. You value financial security and are persistent. You may be stubborn but loyal.",
        "Gemini": "Sun in Gemini makes you communicative, intellectual, and adaptable. You love learning and sharing information but may be restless.",
        "Cancer": "Sun in Cancer indicates a nurturing, emotional, and protective personality. You are attached to home and family.",
        "Leo": "Sun in Leo is in its own sign. You are charismatic, proud, generous, and creative. You seek recognition and respect.",
        "Virgo": "Sun in Virgo makes you analytical, service-oriented, and perfectionist. You pay attention to detail and care about health.",
        "Libra": "Sun in Libra is debilitated. You seek harmony and partnership but may struggle with self-confidence or decision-making.",
        "Scorpio": "Sun in Scorpio gives intensity, willpower, and research ability. You are private and deeply emotional.",
        "Sagittarius": "Sun in Sagittarius makes you optimistic, philosophical, and truth-seeking. You love travel and higher learning.",
        "Capricorn": "Sun in Capricorn gives success through hard work, discipline, and organization. You are ambitious and responsible.",
        "Aquarius": "Sun in Aquarius makes you innovative, humanitarian, and unconventional. You value equality and social causes.",
        "Pisces": "Sun in Pisces gives a compassionate, intuitive, and spiritual nature. You are imaginative but may lack practicality.",
    },
    "Moon": {
        "Aries": "Moon in Aries gives an impulsive, enthusiastic, and independent emotional nature. You react quickly.",
        "Taurus": "Moon in Taurus is exalted. You are emotionally stable, love comfort, and have a good sense of beauty and art.",
        "Gemini": "Moon in Gemini makes your emotions changeable. You rationalize feelings and need intellectual stimulation.",
        "Cancer": "Moon in Cancer is in its own sign. You are deeply intuitive, empathetic, and moody. You nurture others.",
        "Leo": "Moon in Leo makes you dramatic, generous, and warm-hearted. You need attention and affection.",
        "Virgo": "Moon in Virgo gives an analytical emotional nature. You worry easily but are helpful and reliable.",
        "Libra": "Moon in Libra makes you diplomatic and peace-loving. Relationship harmony is essential for your well-being.",
        "Scorpio": "Moon in Scorpio is debilitated. You feel deeply and intensely. You may be possessive or secretive.",
        "Sagittarius": "Moon in Sagittarius makes you optimistic and freedom-loving. You deal with emotions philosophically.",
        "Capricorn": "Moon in Capricorn gives a reserved and cautious emotional nature. You value emotional control.",
        "Aquarius": "Moon in Aquarius makes you detached and friendly. You care about humanity but may seem aloof personally.",
        "Pisces": "Moon in Pisces indicates specific sensitivity, intuition, and dreaminess. You are easily affected by surroundings.",
    },
    "Mars": {
        "Aries": "Mars in Aries is in its own sign. You are courageous, assertive, and energetic. Action-oriented.",
        "Taurus": "Mars in Taurus gives practical energy. You are slow to start but unstoppable once moving. Determined.",
        "Gemini": "Mars in Gemini makes you quick-witted and argumentative. You have scattered energy but sharp intellect.",
        "Cancer": "Mars in Cancer is debilitated. You may express anger passive-aggressively. Emotionally driven actions.",
        "Leo": "Mars in Leo gives leadership ability and creativity. You are passionate and dramatic in action.",
        "Virgo": "Mars in Virgo makes you precise, critical, and efficient. You put energy into work and details.",
        "Libra": "Mars in Libra makes it hard to decide. You fight for justice and peace but may lack direct aggression.",
        "Scorpio": "Mars in Scorpio is in its own sign. You have intense willpower, research ability, and hidden strength.",
        "Sagittarius": "Mars in Sagittarius gives energy for ideals, sports, and travel. You fight for your beliefs.",
        "Capricorn": "Mars in Capricorn is exalted. You have disciplined energy, executive ability, and achieve high goals.",
        "Aquarius": "Mars in Aquarius makes you fight for causes. You act in unconventional ways.",
        "Pisces": "Mars in Pisces gives unsure energy. You may be passive but can fight for spiritual or compassionate reasons.",
    },
    "Mercury": {
        "Aries": "Mercury in Aries gives quick thinking, sharp tongue, and decisiveness. You learn fast.",
        "Taurus": "Mercury in Taurus gives a practical mind. You learn slowly but retain everything. Stubborn intellect.",
        "Gemini": "Mercury in Gemini is in its own sign. You are brilliant, witty, and versatile. A born communicator.",
        "Cancer": "Mercury in Cancer gives an emotional mind. Memory is retentive. Thinking is influenced by feelings.",
        "Leo": "Mercury in Leo gives a dramatic and creative way of speaking. You think big.",
        "Virgo": "Mercury in Virgo is exalted. You are highly analytical, critical, and intelligent. Detail-oriented.",
        "Libra": "Mercury in Libra gives a balanced and diplomatic mind. Good for law and partnerships.",
        "Scorpio": "Mercury in Scorpio gives a researching and probing mind. You love secrets and mysteries.",
        "Sagittarius": "Mercury in Sagittarius can generalize too much. You are philosophical and direct in speech.",
        "Capricorn": "Mercury in Capricorn gives a methodical and calculating mind. Good for administration.",
        "Aquarius": "Mercury in Aquarius gives an inventive and scientific mind. You think ahead of your time.",
        "Pisces": "Mercury in Pisces is debilitated. You think intuitively and practically. Great imagination.",
    },
    "Jupiter": {
        "Aries": "Jupiter in Aries gives belief in self. You are a pioneer in knowledge and philosophy.",
        "Taurus": "Jupiter in Taurus gives practical wisdom. You attract wealth and value resources.",
        "Gemini": "Jupiter in Gemini makes you curious and multi-talented. You love teaching and writing.",
        "Cancer": "Jupiter in Cancer is exalted. You are benevolent, wise, and spiritually inclined. Giving nature.",
        "Leo": "Jupiter in Leo gives a noble and generous spirit. You have strong principles and leadership.",
        "Virgo": "Jupiter in Virgo makes you detail-oriented in wisdom. You like practical service.",
        "Libra": "Jupiter in Libra gives a love for justice and harmony. You are fair-minded.",
        "Scorpio": "Jupiter in Scorpio gives deep occult wisdom. You understand transformation.",
        "Sagittarius": "Jupiter in Sagittarius is in its own sign. You are religious, philosophical, and optimistic.",
        "Capricorn": "Jupiter in Capricorn is debilitated. You may be too practical or materialistic with wisdom.",
        "Aquarius": "Jupiter in Aquarius gives humanitarian wisdom. You care about social progress.",
        "Pisces": "Jupiter in Pisces is in its own sign. You are spiritual, compassionate, and intuitive.",
    },
    "Venus": {
        "Aries": "Venus in Aries gives impulsive and passionate love.You are aggressive in romance.",
        "Taurus": "Venus in Taurus is in its own sign. You love sensual pleasures, beauty, and stability.",
        "Gemini": "Venus in Gemini makes you flirtatious and variety-loving. You value intellectual connection.",
        "Cancer": "Venus in Cancer gives deep emotional attachment. You nurture your partner.",
        "Leo": "Venus in Leo makes you dramatic and loyal in love. You love to be admired.",
        "Virgo": "Venus in Virgo is debilitated. You may be critical in love or shy. Service is your love language.",
        "Libra": "Venus in Libra is in its own sign. You are charming, romantic, and need harmony.",
        "Scorpio": "Venus in Scorpio gives intense, possesive, and transformative love.",
        "Sagittarius": "Venus in Sagittarius makes you adventurous in love. You value freedom.",
        "Capricorn": "Venus in Capricorn gives serious and committed love. You value status.",
        "Aquarius": "Venus in Aquarius makes you unconventional and friendly in love. You value freedom.",
        "Pisces": "Venus in Pisces is exalted. You are universally loving, compassionate, and romantic.",
    },
    "Saturn": {
        "Aries": "Saturn in Aries is debilitated. You may struggle with impulsiveness vs discipline.",
        "Taurus": "Saturn in Taurus gives patience and persistence. You work hard for financial security.",
        "Gemini": "Saturn in Gemini gives disciplined thinking but potential nervousness.",
        "Cancer": "Saturn in Cancer may give emotional inhibition or lack of nurturing early in life.",
        "Leo": "Saturn in Leo indicates struggles with ego and authority.",
        "Virgo": "Saturn in Virgo gives great attention to detail and hard work.",
        "Libra": "Saturn in Libra is exalted. You are fair, disciplined, and responsible in relationships.",
        "Scorpio": "Saturn in Scorpio gives deep resilience and ability to handle crisis.",
        "Sagittarius": "Saturn in Sagittarius gives a serious approach to philosophy and belief.",
        "Capricorn": "Saturn in Capricorn is in its own sign. You are ambitious, organized, and hardworking.",
        "Aquarius": "Saturn in Aquarius is in its own sign. You work hard for social/scientific goals.",
        "Pisces": "Saturn in Pisces gives a need for spiritual discipline. You may feel isolated.",
    },
    "Rahu": {
        "Aries": "Rahu in Aries gives obsession with self and adventure.",
        "Taurus": "Rahu in Taurus gives desire for wealth and luxury.",
        "Gemini": "Rahu in Gemini gives strong desire for communication and information.",
        "Cancer": "Rahu in Cancer gives deep emotional cravings and potential insecurity.",
        "Leo": "Rahu in Leo gives desire for power and fame.",
        "Virgo": "Rahu in Virgo gives obsession with details and health.",
        "Libra": "Rahu in Libra gives obsession with relationships and marketplace.",
        "Scorpio": "Rahu in Scorpio gives obsession with secrets and occult.",
        "Sagittarius": "Rahu in Sagittarius gives unconventional beliefs.",
        "Capricorn": "Rahu in Capricorn gives obsession with career and status.",
        "Aquarius": "Rahu in Aquarius gives obsession with networks and gains.",
        "Pisces": "Rahu in Pisces gives obsession with foreign lands and dreams.",
    },
    "Ketu": {
        "Aries": "Ketu in Aries gives detachment from ego.",
        "Taurus": "Ketu in Taurus gives detachment from family/wealth.",
        "Gemini": "Ketu in Gemini gives detachment from communication.",
        "Cancer": "Ketu in Cancer gives detachment from home/emotions.",
        "Leo": "Ketu in Leo gives detachment from power.",
        "Virgo": "Ketu in Virgo gives detachment from details.",
        "Libra": "Ketu in Libra gives detachment from relationships.",
        "Scorpio": "Ketu in Scorpio gives detachment from occult.",
        "Sagittarius": "Ketu in Sagittarius gives detachment from beliefs.",
        "Capricorn": "Ketu in Capricorn gives detachment from career.",
        "Aquarius": "Ketu in Aquarius gives detachment from gains.",
        "Pisces": "Ketu in Pisces gives spiritual liberation.",
    },
}

PLANETS_IN_HOUSES = {
    "Sun": {
        1: "Sun in 1st House: You have a strong personality, vitality, and leadership qualities. You seek recognition.",
        2: "Sun in 2nd House: You identify with your values and resources. You may speak with authority.",
        3: "Sun in 3rd House: You are courageous and expressive. You may have a strong will.",
        4: "Sun in 4th House: You take pride in your home and heritage. Success comes later in life.",
        5: "Sun in 5th House: You are creative and love center stage. Good for speculation.",
        6: "Sun in 6th House: You are service-oriented and overcome enemies. Health needs watching.",
        7: "Sun in 7th House: You attract strong partners but may have ego conflicts in relationships.",
        8: "Sun in 8th House: You are interested in mysteries and transformation. Vitality fluctuates.",
        9: "Sun in 9th House: You are philosophical and respect tradition. Fortunate with father/guru.",
        10: "Sun in 10th House: Excellent for career and fame. You are a natural leader.",
        11: "Sun in 11th House: You have powerful friends and high gains. Ambitions are realized.",
        12: "Sun in 12th House: You are private and spiritual. You may feel isolated or work behind scenes.",
    },
    "Moon": {
        1: "Moon in 1st House: You are sensitive, compassionate, and your mood affects your health.",
        2: "Moon in 2nd House: Financial fluctuations. You are emotionally attached to family.",
        3: "Moon in 3rd House: You have changes in interests. Good imagination.",
        4: "Moon in 4th House: Strong attachment to mother and home. Emotional security is key.",
        5: "Moon in 5th House: Creative and romantic mind. You love children.",
        6: "Moon in 6th House: Service-oriented but prone to worry and health issues.",
        7: "Moon in 7th House: You seek an emotional connection in partnership. Moods affect marriage.",
        8: "Moon in 8th House: Deep intuition and emotional intensity. Sudden changes.",
        9: "Moon in 9th House: You love travel and have a philosophical mind.",
        10: "Moon in 10th House: Changes in career. You are popular in public.",
        11: "Moon in 11th House: You have many friends and gains come easily.",
        12: "Moon in 12th House: Need for solitude. Spiritual or escapist tendencies.",
    },
    "Mars": {
        1: "Mars in 1st House: Energetic, assertive, and prone to accidents or head injuries.",
        2: "Mars in 2nd House: Sharp speech. You fight for resources.",
        3: "Mars in 3rd House: Courageous and skilled with hands. Issues with younger siblings.",
        4: "Mars in 4th House: Tension in home life. Passionate about property.",
        5: "Mars in 5th House: Intense romance and creative drive. Impulsive with speculation.",
        6: "Mars in 6th House: You defeat enemies and have high immunity.",
        7: "Mars in 7th House: Mangalik Dosha. Possibility of conflict in marriage/partnerships.",
        8: "Mars in 8th House: Intense vitality but risk of sudden events/surgery.",
        9: "Mars in 9th House: You fight for your beliefs. Independent views.",
        10: "Mars in 10th House: Dig Bala (Directional Strength). Excellent for executive career.",
        11: "Mars in 11th House: Wealth through effort. Success in achieving goals.",
        12: "Mars in 12th House: Energy loss or hidden enemies. Good for yoga/martial arts.",
    },
    "Mercury": {
        1: "Mercury in 1st House: Intelligent, humorous, and youthful appearance.",
        2: "Mercury in 2nd House: Good speaker, witty, and good at financial management.",
        3: "Mercury in 3rd House: Skilled writer, communicator, and loves short travels.",
        4: "Mercury in 4th House: Academic degrees, good education, and landed property.",
        5: "Mercury in 5th House: Creative intelligence, good for mantra and advisement.",
        6: "Mercury in 6th House: Analytical mind, good at debate, liable to nervous stress.",
        7: "Mercury in 7th House: Youthful or intelligent partner. Good for business.",
        8: "Mercury in 8th House: Research ability, interest in occult, inheritance.",
        9: "Mercury in 9th House: Higher education, interest in publishing and travel.",
        10: "Mercury in 10th House: Professional success in writing, business, or communication.",
        11: "Mercury in 11th House: Gains through intellect and network.",
        12: "Mercury in 12th House: Imaginative, isolated thinking, foreign residence.",
    },
    "Jupiter": {
        1: "Jupiter in 1st House: Dig Bala. Wisdom, health, protection, and optimism.",
        2: "Jupiter in 2nd House: Wealth, truthful speech, and family happiness.",
        3: "Jupiter in 3rd House: Philosophical communication. Good for siblings.",
        4: "Jupiter in 4th House: Happiness, big home, and good education.",
        5: "Jupiter in 5th House: Intelligence, good children, and past life merit.",
        6: "Jupiter in 6th House: Overcomes enemies with wisdom. Health issues related to liver/sugar.",
        7: "Jupiter in 7th House: Virtuous partner and happy marriage.",
        8: "Jupiter in 8th House: Legacy, occult wisdom, and protection from accidents.",
        9: "Jupiter in 9th House: Religious, lucky, and respect for guru/father.",
        10: "Jupiter in 10th House: Professional respect, teaching, and ethical career.",
        11: "Jupiter in 11th House: Abundant gains and influential friends.",
        12: "Jupiter in 12th House: Spiritual liberation, charitable, and peaceful expenses.",
    },
    "Venus": {
        1: "Venus in 1st House: Charming, beautiful, and charismatic personality.",
        2: "Venus in 2nd House: Wealth, sweet speech, and love of good food/gems.",
        3: "Venus in 3rd House: Artistic skills and good relations with siblings.",
        4: "Venus in 4th House: Dig Bala. Happiness, vehicles, and comfort at home.",
        5: "Venus in 5th House: Romantic, creative, and love for entertainment.",
        6: "Venus in 6th House: Issues in relationships or urinary health. Service oriented.",
        7: "Venus in 7th House: Beautiful partner and focus on relationships.",
        8: "Venus in 8th House: Gains through marriage/partners. Secrets in love.",
        9: "Venus in 9th House: Love of travel and foreign culture. Artistic luck.",
        10: "Venus in 10th House: Career in arts, luxury, or entertainment.",
        11: "Venus in 11th House: Social popularity and gains from women/arts.",
        12: "Venus in 12th House: Bed pleasures, luxury expenses, and isolation.",
    },
    "Saturn": {
        1: "Saturn in 1st House: Serious, disciplined, and mature personality. Delays.",
        2: "Saturn in 2nd House: Frugal, slow accumulation of wealth, harsh speech.",
        3: "Saturn in 3rd House: Persistence and courage. Issues with younger siblings.",
        4: "Saturn in 4th House: Discomfort at home or issues with mother/property.",
        5: "Saturn in 5th House: Restricted romance or delayed children. Serious mind.",
        6: "Saturn in 6th House: Excellent resilience. Defeats enemies slowly.",
        7: "Saturn in 7th House: Dig Bala. Mature partner, delayed marriage, stability.",
        8: "Saturn in 8th House: Long life but chronic issues or difficulties.",
        9: "Saturn in 9th House: Traditional views, issues with father/luck.",
        10: "Saturn in 10th House: Hard work leads to high status. Authority.",
        11: "Saturn in 11th House: Reliable friends, gains come slowly but surely.",
        12: "Saturn in 12th House: Isolation, losses, spiritual discipline necessary.",
    },
    "Rahu": {
        1: "Rahu in 1st House: Unconventional personality, shrewd, desire for recognition.",
        2: "Rahu in 2nd House: Financial ups and downs, unconventional speech.",
        3: "Rahu in 3rd House: Brave and unconventional communication.",
        4: "Rahu in 4th House: Restlessness at home, foreign residence.",
        5: "Rahu in 5th House: Obsessive romance, unconventional children, speculation.",
        6: "Rahu in 6th House: Victory over enemies, health issues usually diagnostic.",
        7: "Rahu in 7th House: Unconventional or foreign partner. Relationship desires.",
        8: "Rahu in 8th House: Interest in occult, sudden events, hidden things.",
        9: "Rahu in 9th House: Unconventional beliefs, rebellion against tradition.",
        10: "Rahu in 10th House: High ambition for career success and fame.",
        11: "Rahu in 11th House: Material gains, large network, successful desires.",
        12: "Rahu in 12th House: Spiritual experiences, sleep issues, foreign lands.",
    },
    "Ketu": {
        1: "Ketu in 1st House: Psychic, intuitive, detached personality.",
        2: "Ketu in 2nd House: Detachment from family/wealth, blunt speech.",
        3: "Ketu in 3rd House: Good spiritual resolve. Issues with communication.",
        4: "Ketu in 4th House: Detached from home/mother. Spiritual peace.",
        5: "Ketu in 5th House: Spiritual intelligence. Issues with children/romance.",
        6: "Ketu in 6th House: Spiritual service, strange health issues.",
        7: "Ketu in 7th House: Detached in relationships. Spiritual partner.",
        8: "Ketu in 8th House: Strong intuition, occult knowledge, sudden research.",
        9: "Ketu in 9th House: Spiritual pilgrimage, detachment from father.",
        10: "Ketu in 10th House: Ups and downs in career, lack of ambition.",
        11: "Ketu in 11th House: Few friends, detachment from gains.",
        12: "Ketu in 12th House: Strong indication for Moksha (liberation). Isolation.",
    }
}
